#!/usr/bin/env bash

TAG_NAME=$1
# TAG_NAME=`wcrypto -v`
PUSH_MSG=${@/$1/}
# PUSH_MSG=${@}

main(){
    git pull origin master
    git add .
    git commit -m "${PUSH_MSG}"
    git push origin master
    git tag ${TAG_NAME}
    git push origin ${TAG_NAME}
}

if [ ! ${TAG_NAME} ]
then
    echo 'UAGE: ./push_tag <tag_name> <push message>'
else
    main
fi
